export const featuredTracks = [
  {
    id: "kaisei-zenya",
    title: "快晴前夜",
    composer: "noale",
    link: "https://youtu.be/BhZg4sj_rPY",
  },
  {
    id: "eureka",
    title: "エウレカ (feat.初音ミク)",
    composer: "ぽんず",
    link: "https://youtu.be/OuwzdDHypug",
  },
  {
    id: "yoru-no-kyo-to",
    title: "夜の教徒 (feat.flower)",
    composer: "neivi",
    link: "https://youtu.be/g_a5l7deaZY",
  },
  {
    id: "ameagari-ni-shoujo",
    title: "雨上がりに少女 (feat.可不)",
    composer: "Tamaco-たまこ",
    link: "https://youtu.be/VE5IsY0hKLc",
  },
  {
    id: "black-out",
    title: "Black Out (feat.GUMI)",
    composer: "*Luna",
    link: "https://youtu.be/PnM_uVGKKl0",
  },
  {
    id: "fear",
    title: "フィア (feat.可不)",
    composer: "Shinba :)",
    link: "https://youtu.be/jdktGLUSr-Q",
  },
  {
    id: "tanne-byou",
    title: "足んねえ病 (feat.初音ミク)",
    composer: "rukaku",
    link: "https://youtu.be/ClRZnke9d54",
  },
  {
    id: "blessing",
    title: "Blessing (feat.VOCALOIDS)",
    composer: "halyosy",
    link: "https://youtu.be/E4tIHBx7bqc",
  },
  {
    id: "kaisei",
    title: "◈*_回生 (feat.UTAU)",
    composer: "ゆくえわっと",
    link: "https://youtu.be/U0YMFCYVzCI",
  },
  {
    id: "cara",
    title: "カーラ (feat.IA)",
    composer: "わもち",
    link: "https://youtu.be/iZ_CNHMXfVE",
  },
  {
    id: "naina-ina-inaina",
    title: "ないな、否、いないな (feat.初音ミク)",
    composer: "TeeN",
    link: "https://youtu.be/MJLx1ABqx6k",
  },
  {
    id: "x",
    title: "X(イクス) (feat.可不)",
    composer: "しぃしぃ / 海野汐音",
    link: "https://youtu.be/LNuY7Xh0m0Y",
  },
  {
    id: "maboroba",
    title: "まほろば (feat.flower)",
    composer: "Violi /ヴィオリ",
    link: "https://youtu.be/25MVef1tA-E",
  },
  {
    id: "nemuri-hime",
    title: "眠り姫 (feat.IA)",
    composer: "Guiano",
    link: "https://youtu.be/8P8VknpWwC8",
  },
  {
    id: "your-hero",
    title: "Your Hero (feat.IA)",
    composer: "wolFer",
    link: "https://youtu.be/x7Qer1TxrkE",
  },
  {
    id: "haru-shigure",
    title: "春時雨 (feat.初音ミク)",
    composer: "夜紗",
    link: "https://youtu.be/ENt8749R1ik",
  },
  {
    id: "negai",
    title: "願い (feat.初音ミク/flower)",
    composer: "はこまるP / HacomaruP",
    link: "https://youtu.be/aTu9Jx769aA",
  },
  {
    id: "hanawo-kou",
    title: "花を恋う (feat.初音ミク)",
    composer: "春海瑞希",
    link: "https://youtu.be/wQlqVbZP0EY",
  },
];
